- id: octowrap
  name: octowrap
  description: Rewrap Python # comments to a specified line length
  entry: octowrap
  language: python
  types: [python]
- id: octowrap-check
  name: octowrap-check
  description: Fail if any Python # comments would be rewrapped, without modifying them
  entry: octowrap --check
  language: python
  types: [python]
